CREATE DATABASE DIGITAL_ASSET_MANAGEMENT

USE DIGITAL_ASSET_MANAGEMENT

--1.EMPLOYEES TABLE
CREATE TABLE EMPLOYEES(
EMPLOYEEID INT IDENTITY(1,1) PRIMARY KEY,
NAMES VARCHAR(50),
DEPARTMENT VARCHAR(20),
EMAIL VARCHAR(50) UNIQUE,
PASSWORDS VARCHAR(20));

--2.ASSETS TABLE
CREATE TABLE ASSETS(
ASSETID INT IDENTITY(1,1) PRIMARY KEY,
NAMES VARCHAR(50),
TYPE VARCHAR(50),
SERIALNUMBER INT UNIQUE,
PURCHASEDATE DATE,
LOCATIONS VARCHAR(50),
STATUS VARCHAR(50),
OWNERID INT,
CONSTRAINT FK_OWNER
FOREIGN KEY(OWNERID)REFERENCES EMPLOYEES(EMPLOYEEID));

--3.MAINTENANCE RECORDS TABLE
CREATE TABLE MAINTENANCE_RECORDS(
MAINTENANCEID INT IDENTITY(1,1) PRIMARY KEY,
ASSETID INT,
MAINTENANCEDATE DATE,
DESCRIPTION VARCHAR(60),
COST DECIMAL(10,2)
FOREIGN KEY(ASSETID)REFERENCES ASSETS(ASSETID)
);

--4.ASSET ALLOCATIONS TABLE
CREATE TABLE ASSET_ALLOCATIONS(
ALLOCATIONID INT IDENTITY(1,1) PRIMARY KEY,
ASSETID INT,
EMPLOYEEID INT,
ALLOCATIONDATE DATE,
RETURNDATE DATE,
FOREIGN KEY(ASSETID)REFERENCES ASSETS(ASSETID),
FOREIGN KEY(EMPLOYEEID)REFERENCES EMPLOYEES(EMPLOYEEID));


--5.RESERVATION TABLE
CREATE TABLE RESERVATIONS(
RESERVATIONID INT IDENTITY(1,1) PRIMARY KEY,
ASSETID INT,
EMPLOYEEID INT,
RESERVATIONDATE DATE,
STARTDATE DATE,
ENDDATE DATE,
STATUS VARCHAR(50),
FOREIGN KEY (ASSETID)REFERENCES ASSETS(ASSETID),
FOREIGN KEY (EMPLOYEEID)REFERENCES EMPLOYEES(EMPLOYEEID));